#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Reservas_de_Eventos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDEventos")]
	public partial class EventosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTEventos(TEventos instance);
    partial void UpdateTEventos(TEventos instance);
    partial void DeleteTEventos(TEventos instance);
    partial void InsertTUsuarios(TUsuarios instance);
    partial void UpdateTUsuarios(TUsuarios instance);
    partial void DeleteTUsuarios(TUsuarios instance);
    partial void InsertTPerfiles_usuarios(TPerfiles_usuarios instance);
    partial void UpdateTPerfiles_usuarios(TPerfiles_usuarios instance);
    partial void DeleteTPerfiles_usuarios(TPerfiles_usuarios instance);
    partial void InsertTReportes(TReportes instance);
    partial void UpdateTReportes(TReportes instance);
    partial void DeleteTReportes(TReportes instance);
    partial void InsertTReservas(TReservas instance);
    partial void UpdateTReservas(TReservas instance);
    partial void DeleteTReservas(TReservas instance);
    partial void InsertTUbicaciones(TUbicaciones instance);
    partial void UpdateTUbicaciones(TUbicaciones instance);
    partial void DeleteTUbicaciones(TUbicaciones instance);
    #endregion
		
		public EventosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TEventos> TEventos
		{
			get
			{
				return this.GetTable<TEventos>();
			}
		}
		
		public System.Data.Linq.Table<TUsuarios> TUsuarios
		{
			get
			{
				return this.GetTable<TUsuarios>();
			}
		}
		
		public System.Data.Linq.Table<TPerfiles_usuarios> TPerfiles_usuarios
		{
			get
			{
				return this.GetTable<TPerfiles_usuarios>();
			}
		}
		
		public System.Data.Linq.Table<TReportes> TReportes
		{
			get
			{
				return this.GetTable<TReportes>();
			}
		}
		
		public System.Data.Linq.Table<TReservas> TReservas
		{
			get
			{
				return this.GetTable<TReservas>();
			}
		}
		
		public System.Data.Linq.Table<TUbicaciones> TUbicaciones
		{
			get
			{
				return this.GetTable<TUbicaciones>();
			}
		}
		
		public System.Data.Linq.Table<eventos_populares> eventos_populares
		{
			get
			{
				return this.GetTable<eventos_populares>();
			}
		}
		
		public System.Data.Linq.Table<estadisticas_participacion_evento> estadisticas_participacion_evento
		{
			get
			{
				return this.GetTable<estadisticas_participacion_evento>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarEvento")]
		public int sp_ActualizarEvento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> evento_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_evento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> hora_inicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> hora_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ubicacion_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string creado_por)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), evento_id, titulo, descripcion, fecha_evento, hora_inicio, hora_fin, ubicacion_id, creado_por);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ValidarUsuario")]
		public ISingleResult<sp_ValidarUsuarioResult> sp_ValidarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_usuario, contrasena);
			return ((ISingleResult<sp_ValidarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarPerfilUsuario")]
		public int sp_ActualizarPerfilUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> perfil_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), perfil_id, nombre, apellido, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarReserva")]
		public int sp_ActualizarReserva([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reserva_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reserva_id, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarUbicacion")]
		public int sp_ActualizarUbicacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ubicacion_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string nombre_ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string codigo_postal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ubicacion_id, nombre_ubicacion, direccion, ciudad, estado, codigo_postal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarUsuario")]
		public int sp_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo_electronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario_id, nombre_usuario, contrasena, correo_electronico, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarEventosPorFecha")]
		public ISingleResult<sp_BuscarEventosPorFechaResult> sp_BuscarEventosPorFecha([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_evento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha_evento);
			return ((ISingleResult<sp_BuscarEventosPorFechaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarEventosPorTitulo")]
		public ISingleResult<sp_BuscarEventosPorTituloResult> sp_BuscarEventosPorTitulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string titulo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo);
			return ((ISingleResult<sp_BuscarEventosPorTituloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarPerfilesPorApellido")]
		public ISingleResult<sp_BuscarPerfilesPorApellidoResult> sp_BuscarPerfilesPorApellido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string apellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apellido);
			return ((ISingleResult<sp_BuscarPerfilesPorApellidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarPerfilesPorNombre")]
		public ISingleResult<sp_BuscarPerfilesPorNombreResult> sp_BuscarPerfilesPorNombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<sp_BuscarPerfilesPorNombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarReservasPorEvento")]
		public ISingleResult<sp_BuscarReservasPorEventoResult> sp_BuscarReservasPorEvento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> evento_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), evento_id);
			return ((ISingleResult<sp_BuscarReservasPorEventoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarReservasPorUsuario")]
		public ISingleResult<sp_BuscarReservasPorUsuarioResult> sp_BuscarReservasPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario);
			return ((ISingleResult<sp_BuscarReservasPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarUbicacionesPorNombre")]
		public ISingleResult<sp_BuscarUbicacionesPorNombreResult> sp_BuscarUbicacionesPorNombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string nombre_ubicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_ubicacion);
			return ((ISingleResult<sp_BuscarUbicacionesPorNombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarUsuariosPorCorreo")]
		public ISingleResult<sp_BuscarUsuariosPorCorreoResult> sp_BuscarUsuariosPorCorreo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo_electronico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo_electronico);
			return ((ISingleResult<sp_BuscarUsuariosPorCorreoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BuscarUsuariosPorNombre")]
		public ISingleResult<sp_BuscarUsuariosPorNombreResult> sp_BuscarUsuariosPorNombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre_usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_usuario);
			return ((ISingleResult<sp_BuscarUsuariosPorNombreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearEvento")]
		public int sp_CrearEvento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_evento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> hora_inicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> hora_fin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ubicacion_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string creado_por)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, descripcion, fecha_evento, hora_inicio, hora_fin, ubicacion_id, creado_por);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearPerfilUsuario")]
		public int sp_CrearPerfilUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario_id, nombre, apellido, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearReserva")]
		public int sp_CrearReserva([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> evento_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, evento_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearUbicacion")]
		public int sp_CrearUbicacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string nombre_ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string codigo_postal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_ubicacion, direccion, ciudad, estado, codigo_postal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CrearUsuario")]
		public int sp_CrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo_electronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_usuario, contrasena, correo_electronico, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarEvento")]
		public int sp_EliminarEvento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> evento_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), evento_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarPerfilUsuario")]
		public int sp_EliminarPerfilUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> perfil_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), perfil_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarReserva")]
		public int sp_EliminarReserva([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reserva_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reserva_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarUbicacion")]
		public int sp_EliminarUbicacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ubicacion_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ubicacion_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarUsuario")]
		public int sp_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerEventos")]
		public ISingleResult<sp_LeerEventosResult> sp_LeerEventos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LeerEventosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerPerfilesUsuarios")]
		public ISingleResult<sp_LeerPerfilesUsuariosResult> sp_LeerPerfilesUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LeerPerfilesUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerReservas")]
		public ISingleResult<sp_LeerReservasResult> sp_LeerReservas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LeerReservasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerUbicaciones")]
		public ISingleResult<sp_LeerUbicacionesResult> sp_LeerUbicaciones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LeerUbicacionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerUsuarioPorID")]
		public ISingleResult<sp_LeerUsuarioPorIDResult> sp_LeerUsuarioPorID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario_id);
			return ((ISingleResult<sp_LeerUsuarioPorIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LeerUsuarios")]
		public ISingleResult<sp_LeerUsuariosResult> sp_LeerUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LeerUsuariosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEventos")]
	public partial class TEventos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _evento_id;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.DateTime _fecha_evento;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private System.Nullable<int> _ubicacion_id;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		private EntitySet<TReportes> _TReportes;
		
		private EntitySet<TReservas> _TReservas;
		
		private EntityRef<TUbicaciones> _TUbicaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onevento_idChanging(int value);
    partial void Onevento_idChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_eventoChanging(System.DateTime value);
    partial void Onfecha_eventoChanged();
    partial void Onhora_inicioChanging(System.TimeSpan value);
    partial void Onhora_inicioChanged();
    partial void Onhora_finChanging(System.TimeSpan value);
    partial void Onhora_finChanged();
    partial void Onubicacion_idChanging(System.Nullable<int> value);
    partial void Onubicacion_idChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Onfecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_creacionChanged();
    #endregion
		
		public TEventos()
		{
			this._TReportes = new EntitySet<TReportes>(new Action<TReportes>(this.attach_TReportes), new Action<TReportes>(this.detach_TReportes));
			this._TReservas = new EntitySet<TReservas>(new Action<TReservas>(this.attach_TReservas), new Action<TReservas>(this.detach_TReservas));
			this._TUbicaciones = default(EntityRef<TUbicaciones>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this.Onevento_idChanging(value);
					this.SendPropertyChanging();
					this._evento_id = value;
					this.SendPropertyChanged("evento_id");
					this.Onevento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_evento", DbType="Date NOT NULL")]
		public System.DateTime fecha_evento
		{
			get
			{
				return this._fecha_evento;
			}
			set
			{
				if ((this._fecha_evento != value))
				{
					this.Onfecha_eventoChanging(value);
					this.SendPropertyChanging();
					this._fecha_evento = value;
					this.SendPropertyChanged("fecha_evento");
					this.Onfecha_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this.Onhora_inicioChanging(value);
					this.SendPropertyChanging();
					this._hora_inicio = value;
					this.SendPropertyChanged("hora_inicio");
					this.Onhora_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this.Onhora_finChanging(value);
					this.SendPropertyChanging();
					this._hora_fin = value;
					this.SendPropertyChanged("hora_fin");
					this.Onhora_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int")]
		public System.Nullable<int> ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					if (this._TUbicaciones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onubicacion_idChanging(value);
					this.SendPropertyChanging();
					this._ubicacion_id = value;
					this.SendPropertyChanged("ubicacion_id");
					this.Onubicacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="NVarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEventos_TReportes", Storage="_TReportes", ThisKey="evento_id", OtherKey="evento_id")]
		public EntitySet<TReportes> TReportes
		{
			get
			{
				return this._TReportes;
			}
			set
			{
				this._TReportes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEventos_TReservas", Storage="_TReservas", ThisKey="evento_id", OtherKey="evento_id")]
		public EntitySet<TReservas> TReservas
		{
			get
			{
				return this._TReservas;
			}
			set
			{
				this._TReservas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUbicaciones_TEventos", Storage="_TUbicaciones", ThisKey="ubicacion_id", OtherKey="ubicacion_id", IsForeignKey=true, DeleteRule="SET NULL")]
		public TUbicaciones TUbicaciones
		{
			get
			{
				return this._TUbicaciones.Entity;
			}
			set
			{
				TUbicaciones previousValue = this._TUbicaciones.Entity;
				if (((previousValue != value) 
							|| (this._TUbicaciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUbicaciones.Entity = null;
						previousValue.TEventos.Remove(this);
					}
					this._TUbicaciones.Entity = value;
					if ((value != null))
					{
						value.TEventos.Add(this);
						this._ubicacion_id = value.ubicacion_id;
					}
					else
					{
						this._ubicacion_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TUbicaciones");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TReportes(TReportes entity)
		{
			this.SendPropertyChanging();
			entity.TEventos = this;
		}
		
		private void detach_TReportes(TReportes entity)
		{
			this.SendPropertyChanging();
			entity.TEventos = null;
		}
		
		private void attach_TReservas(TReservas entity)
		{
			this.SendPropertyChanging();
			entity.TEventos = this;
		}
		
		private void detach_TReservas(TReservas entity)
		{
			this.SendPropertyChanging();
			entity.TEventos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuarios")]
	public partial class TUsuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuario_id;
		
		private string _nombre_usuario;
		
		private System.Data.Linq.Binary _contrasena;
		
		private string _correo_electronico;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		private string _rol;
		
		private EntitySet<TPerfiles_usuarios> _TPerfiles_usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OncontrasenaChanging(System.Data.Linq.Binary value);
    partial void OncontrasenaChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void Onfecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_creacionChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    #endregion
		
		public TUsuarios()
		{
			this._TPerfiles_usuarios = new EntitySet<TPerfiles_usuarios>(new Action<TPerfiles_usuarios>(this.attach_TPerfiles_usuarios), new Action<TPerfiles_usuarios>(this.detach_TPerfiles_usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarBinary(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuarios_TPerfiles_usuarios", Storage="_TPerfiles_usuarios", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<TPerfiles_usuarios> TPerfiles_usuarios
		{
			get
			{
				return this._TPerfiles_usuarios;
			}
			set
			{
				this._TPerfiles_usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TPerfiles_usuarios(TPerfiles_usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TUsuarios = this;
		}
		
		private void detach_TPerfiles_usuarios(TPerfiles_usuarios entity)
		{
			this.SendPropertyChanging();
			entity.TUsuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPerfiles_usuarios")]
	public partial class TPerfiles_usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _perfil_id;
		
		private System.Nullable<int> _usuario_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _telefono;
		
		private string _direccion;
		
		private EntityRef<TUsuarios> _TUsuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onperfil_idChanging(int value);
    partial void Onperfil_idChanged();
    partial void Onusuario_idChanging(System.Nullable<int> value);
    partial void Onusuario_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public TPerfiles_usuarios()
		{
			this._TUsuarios = default(EntityRef<TUsuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int perfil_id
		{
			get
			{
				return this._perfil_id;
			}
			set
			{
				if ((this._perfil_id != value))
				{
					this.Onperfil_idChanging(value);
					this.SendPropertyChanging();
					this._perfil_id = value;
					this.SendPropertyChanged("perfil_id");
					this.Onperfil_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._TUsuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuarios_TPerfiles_usuarios", Storage="_TUsuarios", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TUsuarios TUsuarios
		{
			get
			{
				return this._TUsuarios.Entity;
			}
			set
			{
				TUsuarios previousValue = this._TUsuarios.Entity;
				if (((previousValue != value) 
							|| (this._TUsuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUsuarios.Entity = null;
						previousValue.TPerfiles_usuarios.Remove(this);
					}
					this._TUsuarios.Entity = value;
					if ((value != null))
					{
						value.TPerfiles_usuarios.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TUsuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TReportes")]
	public partial class TReportes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reporte_id;
		
		private System.Nullable<int> _evento_id;
		
		private System.Nullable<int> _total_reservas;
		
		private System.Nullable<int> _total_participacion;
		
		private System.Nullable<System.DateTime> _fecha_reporte;
		
		private EntityRef<TEventos> _TEventos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreporte_idChanging(int value);
    partial void Onreporte_idChanged();
    partial void Onevento_idChanging(System.Nullable<int> value);
    partial void Onevento_idChanged();
    partial void Ontotal_reservasChanging(System.Nullable<int> value);
    partial void Ontotal_reservasChanged();
    partial void Ontotal_participacionChanging(System.Nullable<int> value);
    partial void Ontotal_participacionChanged();
    partial void Onfecha_reporteChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reporteChanged();
    #endregion
		
		public TReportes()
		{
			this._TEventos = default(EntityRef<TEventos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reporte_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int reporte_id
		{
			get
			{
				return this._reporte_id;
			}
			set
			{
				if ((this._reporte_id != value))
				{
					this.Onreporte_idChanging(value);
					this.SendPropertyChanging();
					this._reporte_id = value;
					this.SendPropertyChanged("reporte_id");
					this.Onreporte_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int")]
		public System.Nullable<int> evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					if (this._TEventos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onevento_idChanging(value);
					this.SendPropertyChanging();
					this._evento_id = value;
					this.SendPropertyChanged("evento_id");
					this.Onevento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_reservas", DbType="Int")]
		public System.Nullable<int> total_reservas
		{
			get
			{
				return this._total_reservas;
			}
			set
			{
				if ((this._total_reservas != value))
				{
					this.Ontotal_reservasChanging(value);
					this.SendPropertyChanging();
					this._total_reservas = value;
					this.SendPropertyChanged("total_reservas");
					this.Ontotal_reservasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_participacion", DbType="Int")]
		public System.Nullable<int> total_participacion
		{
			get
			{
				return this._total_participacion;
			}
			set
			{
				if ((this._total_participacion != value))
				{
					this.Ontotal_participacionChanging(value);
					this.SendPropertyChanging();
					this._total_participacion = value;
					this.SendPropertyChanged("total_participacion");
					this.Ontotal_participacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reporte", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reporte
		{
			get
			{
				return this._fecha_reporte;
			}
			set
			{
				if ((this._fecha_reporte != value))
				{
					this.Onfecha_reporteChanging(value);
					this.SendPropertyChanging();
					this._fecha_reporte = value;
					this.SendPropertyChanged("fecha_reporte");
					this.Onfecha_reporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEventos_TReportes", Storage="_TEventos", ThisKey="evento_id", OtherKey="evento_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TEventos TEventos
		{
			get
			{
				return this._TEventos.Entity;
			}
			set
			{
				TEventos previousValue = this._TEventos.Entity;
				if (((previousValue != value) 
							|| (this._TEventos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TEventos.Entity = null;
						previousValue.TReportes.Remove(this);
					}
					this._TEventos.Entity = value;
					if ((value != null))
					{
						value.TReportes.Add(this);
						this._evento_id = value.evento_id;
					}
					else
					{
						this._evento_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TEventos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TReservas")]
	public partial class TReservas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reserva_id;
		
		private string _usuario;
		
		private System.Nullable<int> _evento_id;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		private EntityRef<TEventos> _TEventos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreserva_idChanging(int value);
    partial void Onreserva_idChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void Onevento_idChanging(System.Nullable<int> value);
    partial void Onevento_idChanged();
    partial void Onfecha_reservaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reservaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public TReservas()
		{
			this._TEventos = default(EntityRef<TEventos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserva_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int reserva_id
		{
			get
			{
				return this._reserva_id;
			}
			set
			{
				if ((this._reserva_id != value))
				{
					this.Onreserva_idChanging(value);
					this.SendPropertyChanging();
					this._reserva_id = value;
					this.SendPropertyChanged("reserva_id");
					this.Onreserva_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int")]
		public System.Nullable<int> evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					if (this._TEventos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onevento_idChanging(value);
					this.SendPropertyChanging();
					this._evento_id = value;
					this.SendPropertyChanged("evento_id");
					this.Onevento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this.Onfecha_reservaChanging(value);
					this.SendPropertyChanging();
					this._fecha_reserva = value;
					this.SendPropertyChanged("fecha_reserva");
					this.Onfecha_reservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEventos_TReservas", Storage="_TEventos", ThisKey="evento_id", OtherKey="evento_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TEventos TEventos
		{
			get
			{
				return this._TEventos.Entity;
			}
			set
			{
				TEventos previousValue = this._TEventos.Entity;
				if (((previousValue != value) 
							|| (this._TEventos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TEventos.Entity = null;
						previousValue.TReservas.Remove(this);
					}
					this._TEventos.Entity = value;
					if ((value != null))
					{
						value.TReservas.Add(this);
						this._evento_id = value.evento_id;
					}
					else
					{
						this._evento_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TEventos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUbicaciones")]
	public partial class TUbicaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ubicacion_id;
		
		private string _nombre_ubicacion;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _estado;
		
		private string _codigo_postal;
		
		private EntitySet<TEventos> _TEventos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onubicacion_idChanging(int value);
    partial void Onubicacion_idChanged();
    partial void Onnombre_ubicacionChanging(string value);
    partial void Onnombre_ubicacionChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Oncodigo_postalChanging(string value);
    partial void Oncodigo_postalChanged();
    #endregion
		
		public TUbicaciones()
		{
			this._TEventos = new EntitySet<TEventos>(new Action<TEventos>(this.attach_TEventos), new Action<TEventos>(this.detach_TEventos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this.Onubicacion_idChanging(value);
					this.SendPropertyChanging();
					this._ubicacion_id = value;
					this.SendPropertyChanged("ubicacion_id");
					this.Onubicacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ubicacion", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre_ubicacion
		{
			get
			{
				return this._nombre_ubicacion;
			}
			set
			{
				if ((this._nombre_ubicacion != value))
				{
					this.Onnombre_ubicacionChanging(value);
					this.SendPropertyChanging();
					this._nombre_ubicacion = value;
					this.SendPropertyChanged("nombre_ubicacion");
					this.Onnombre_ubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="NVarChar(100)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(100)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_postal", DbType="NVarChar(20)")]
		public string codigo_postal
		{
			get
			{
				return this._codigo_postal;
			}
			set
			{
				if ((this._codigo_postal != value))
				{
					this.Oncodigo_postalChanging(value);
					this.SendPropertyChanging();
					this._codigo_postal = value;
					this.SendPropertyChanged("codigo_postal");
					this.Oncodigo_postalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUbicaciones_TEventos", Storage="_TEventos", ThisKey="ubicacion_id", OtherKey="ubicacion_id")]
		public EntitySet<TEventos> TEventos
		{
			get
			{
				return this._TEventos;
			}
			set
			{
				this._TEventos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TEventos(TEventos entity)
		{
			this.SendPropertyChanging();
			entity.TUbicaciones = this;
		}
		
		private void detach_TEventos(TEventos entity)
		{
			this.SendPropertyChanging();
			entity.TUbicaciones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eventos_populares")]
	public partial class eventos_populares
	{
		
		private int _evento_id;
		
		private string _titulo;
		
		private System.Nullable<int> _total_reservas;
		
		public eventos_populares()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int NOT NULL")]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_reservas", DbType="Int")]
		public System.Nullable<int> total_reservas
		{
			get
			{
				return this._total_reservas;
			}
			set
			{
				if ((this._total_reservas != value))
				{
					this._total_reservas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.estadisticas_participacion_evento")]
	public partial class estadisticas_participacion_evento
	{
		
		private int _evento_id;
		
		private string _titulo;
		
		private System.Nullable<int> _total_participacion;
		
		public estadisticas_participacion_evento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int NOT NULL")]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_participacion", DbType="Int")]
		public System.Nullable<int> total_participacion
		{
			get
			{
				return this._total_participacion;
			}
			set
			{
				if ((this._total_participacion != value))
				{
					this._total_participacion = value;
				}
			}
		}
	}
	
	public partial class sp_ValidarUsuarioResult
	{
		
		private string _Rol;
		
		private System.Nullable<int> _CodError;
		
		private string _Mensaje;
		
		public sp_ValidarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="NVarChar(50)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int")]
		public System.Nullable<int> CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="NVarChar(100)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarEventosPorFechaResult
	{
		
		private int _evento_id;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.DateTime _fecha_evento;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private System.Nullable<int> _ubicacion_id;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		public sp_BuscarEventosPorFechaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int NOT NULL")]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_evento", DbType="Date NOT NULL")]
		public System.DateTime fecha_evento
		{
			get
			{
				return this._fecha_evento;
			}
			set
			{
				if ((this._fecha_evento != value))
				{
					this._fecha_evento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this._hora_inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this._hora_fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int")]
		public System.Nullable<int> ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this._ubicacion_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="NVarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this._creado_por = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this._fecha_creacion = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarEventosPorTituloResult
	{
		
		private int _evento_id;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.DateTime _fecha_evento;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private System.Nullable<int> _ubicacion_id;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		public sp_BuscarEventosPorTituloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int NOT NULL")]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_evento", DbType="Date NOT NULL")]
		public System.DateTime fecha_evento
		{
			get
			{
				return this._fecha_evento;
			}
			set
			{
				if ((this._fecha_evento != value))
				{
					this._fecha_evento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this._hora_inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this._hora_fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int")]
		public System.Nullable<int> ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this._ubicacion_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="NVarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this._creado_por = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this._fecha_creacion = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarPerfilesPorApellidoResult
	{
		
		private int _perfil_id;
		
		private System.Nullable<int> _usuario_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _telefono;
		
		private string _direccion;
		
		public sp_BuscarPerfilesPorApellidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_id", DbType="Int NOT NULL")]
		public int perfil_id
		{
			get
			{
				return this._perfil_id;
			}
			set
			{
				if ((this._perfil_id != value))
				{
					this._perfil_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarPerfilesPorNombreResult
	{
		
		private int _perfil_id;
		
		private System.Nullable<int> _usuario_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _telefono;
		
		private string _direccion;
		
		public sp_BuscarPerfilesPorNombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_id", DbType="Int NOT NULL")]
		public int perfil_id
		{
			get
			{
				return this._perfil_id;
			}
			set
			{
				if ((this._perfil_id != value))
				{
					this._perfil_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarReservasPorEventoResult
	{
		
		private int _reserva_id;
		
		private string _usuario;
		
		private System.Nullable<int> _evento_id;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		public sp_BuscarReservasPorEventoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserva_id", DbType="Int NOT NULL")]
		public int reserva_id
		{
			get
			{
				return this._reserva_id;
			}
			set
			{
				if ((this._reserva_id != value))
				{
					this._reserva_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int")]
		public System.Nullable<int> evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this._fecha_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarReservasPorUsuarioResult
	{
		
		private int _reserva_id;
		
		private string _usuario;
		
		private System.Nullable<int> _evento_id;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		public sp_BuscarReservasPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserva_id", DbType="Int NOT NULL")]
		public int reserva_id
		{
			get
			{
				return this._reserva_id;
			}
			set
			{
				if ((this._reserva_id != value))
				{
					this._reserva_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int")]
		public System.Nullable<int> evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this._fecha_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarUbicacionesPorNombreResult
	{
		
		private int _ubicacion_id;
		
		private string _nombre_ubicacion;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _estado;
		
		private string _codigo_postal;
		
		public sp_BuscarUbicacionesPorNombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int NOT NULL")]
		public int ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this._ubicacion_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ubicacion", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre_ubicacion
		{
			get
			{
				return this._nombre_ubicacion;
			}
			set
			{
				if ((this._nombre_ubicacion != value))
				{
					this._nombre_ubicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="NVarChar(100)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this._ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(100)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_postal", DbType="NVarChar(20)")]
		public string codigo_postal
		{
			get
			{
				return this._codigo_postal;
			}
			set
			{
				if ((this._codigo_postal != value))
				{
					this._codigo_postal = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarUsuariosPorCorreoResult
	{
		
		private int _usuario_id;
		
		private string _nombre_usuario;
		
		private System.Data.Linq.Binary _contrasena;
		
		private string _correo_electronico;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		private string _rol;
		
		public sp_BuscarUsuariosPorCorreoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this._nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarBinary(255) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this._correo_electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this._fecha_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
	}
	
	public partial class sp_BuscarUsuariosPorNombreResult
	{
		
		private int _usuario_id;
		
		private string _nombre_usuario;
		
		private System.Data.Linq.Binary _contrasena;
		
		private string _correo_electronico;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		private string _rol;
		
		public sp_BuscarUsuariosPorNombreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this._nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarBinary(255) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this._correo_electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this._fecha_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
	}
	
	public partial class sp_LeerEventosResult
	{
		
		private int _evento_id;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.DateTime _fecha_evento;
		
		private System.TimeSpan _hora_inicio;
		
		private System.TimeSpan _hora_fin;
		
		private System.Nullable<int> _ubicacion_id;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		public sp_LeerEventosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int NOT NULL")]
		public int evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_evento", DbType="Date NOT NULL")]
		public System.DateTime fecha_evento
		{
			get
			{
				return this._fecha_evento;
			}
			set
			{
				if ((this._fecha_evento != value))
				{
					this._fecha_evento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_inicio", DbType="Time NOT NULL")]
		public System.TimeSpan hora_inicio
		{
			get
			{
				return this._hora_inicio;
			}
			set
			{
				if ((this._hora_inicio != value))
				{
					this._hora_inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_fin", DbType="Time NOT NULL")]
		public System.TimeSpan hora_fin
		{
			get
			{
				return this._hora_fin;
			}
			set
			{
				if ((this._hora_fin != value))
				{
					this._hora_fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int")]
		public System.Nullable<int> ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this._ubicacion_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="NVarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this._creado_por = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this._fecha_creacion = value;
				}
			}
		}
	}
	
	public partial class sp_LeerPerfilesUsuariosResult
	{
		
		private int _perfil_id;
		
		private System.Nullable<int> _usuario_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _telefono;
		
		private string _direccion;
		
		public sp_LeerPerfilesUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_id", DbType="Int NOT NULL")]
		public int perfil_id
		{
			get
			{
				return this._perfil_id;
			}
			set
			{
				if ((this._perfil_id != value))
				{
					this._perfil_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
	}
	
	public partial class sp_LeerReservasResult
	{
		
		private int _reserva_id;
		
		private string _usuario;
		
		private System.Nullable<int> _evento_id;
		
		private System.Nullable<System.DateTime> _fecha_reserva;
		
		private string _estado;
		
		public sp_LeerReservasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserva_id", DbType="Int NOT NULL")]
		public int reserva_id
		{
			get
			{
				return this._reserva_id;
			}
			set
			{
				if ((this._reserva_id != value))
				{
					this._reserva_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evento_id", DbType="Int")]
		public System.Nullable<int> evento_id
		{
			get
			{
				return this._evento_id;
			}
			set
			{
				if ((this._evento_id != value))
				{
					this._evento_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reserva", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reserva
		{
			get
			{
				return this._fecha_reserva;
			}
			set
			{
				if ((this._fecha_reserva != value))
				{
					this._fecha_reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
	
	public partial class sp_LeerUbicacionesResult
	{
		
		private int _ubicacion_id;
		
		private string _nombre_ubicacion;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _estado;
		
		private string _codigo_postal;
		
		public sp_LeerUbicacionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion_id", DbType="Int NOT NULL")]
		public int ubicacion_id
		{
			get
			{
				return this._ubicacion_id;
			}
			set
			{
				if ((this._ubicacion_id != value))
				{
					this._ubicacion_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ubicacion", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre_ubicacion
		{
			get
			{
				return this._nombre_ubicacion;
			}
			set
			{
				if ((this._nombre_ubicacion != value))
				{
					this._nombre_ubicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="NVarChar(100)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this._ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(100)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_postal", DbType="NVarChar(20)")]
		public string codigo_postal
		{
			get
			{
				return this._codigo_postal;
			}
			set
			{
				if ((this._codigo_postal != value))
				{
					this._codigo_postal = value;
				}
			}
		}
	}
	
	public partial class sp_LeerUsuarioPorIDResult
	{
		
		private int _usuario_id;
		
		private string _nombre_usuario;
		
		private string _correo_electronico;
		
		private string _rol;
		
		private string _contrasena;
		
		public sp_LeerUsuarioPorIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this._nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this._correo_electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="NVarChar(MAX)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
	}
	
	public partial class sp_LeerUsuariosResult
	{
		
		private int _usuario_id;
		
		private string _nombre_usuario;
		
		private string _correo_electronico;
		
		private string _rol;
		
		private string _contrasena;
		
		public sp_LeerUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this._usuario_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this._nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this._correo_electronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="NVarChar(MAX)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
